instancesDb = {
    [532] = { instanceID = 532, instanceName = "Karazhan", savedInstanceName = "Karazhan", instanceIndex = 1 },
    [565] = { instanceID = 565, instanceName = "Gruul's Lair", savedInstanceName = "Gruul's Lair", instanceIndex = 2 },
    [544] = { instanceID = 544, instanceName = "Magtheridon's Lair", savedInstanceName = "Magtheridon's Lair", instanceIndex = 3 },
    [548] = { instanceID = 548, instanceName = "Serpentshrine Cavern", savedInstanceName = "Serpentshrine Cavern", instanceIndex = 4 },
    [550] = { instanceID = 550, instanceName = "Tempest Keep", savedInstanceName = "The Eye", instanceIndex = 5 },
    [534] = { instanceID = 534, instanceName = "Hyjal Summit", savedInstanceName = "The Battle for Mount Hyjal", instanceIndex = 6 },
    [564] = { instanceID = 564, instanceName = "Black Temple", savedInstanceName = "Black Temple", instanceIndex = 7 },
    [568] = { instanceID = 568, instanceName = "Zul'Aman", savedInstanceName = "Zul'Aman", instanceIndex = 8 },
    [580] = { instanceID = 580, instanceName = "Sunwell Plateau", savedInstanceName = "The Sunwell", instanceIndex = 9 },
}

encountersDb = {
    [652] = { encounterID = 652, encounterName = "Attumen the Huntsman", instanceID = 532, alternativeTargets = {}, encounterIndex = 1 },
    [653] = { encounterID = 653, encounterName = "Moroes", instanceID = 532, alternativeTargets = {}, encounterIndex = 2 },
    [654] = { encounterID = 654, encounterName = "Maiden of Virtue", instanceID = 532, alternativeTargets = {}, encounterIndex = 3 },
    [655] = { encounterID = 655, encounterName = "Opera Hall", instanceID = 532, alternativeTargets = {}, encounterIndex = 4 },
    [662] = { encounterID = 662, encounterName = "Nightbane", instanceID = 532, alternativeTargets = {}, encounterIndex = 5 },
    [656] = { encounterID = 656, encounterName = "The Curator", instanceID = 532, alternativeTargets = {}, encounterIndex = 6 },
    [657] = { encounterID = 657, encounterName = "Terestian Illhoof", instanceID = 532, alternativeTargets = {}, encounterIndex = 7 },
    [658] = { encounterID = 658, encounterName = "Shade of Aran", instanceID = 532, alternativeTargets = {}, encounterIndex = 8 },
    [659] = { encounterID = 659, encounterName = "Netherspite", instanceID = 532, alternativeTargets = {}, encounterIndex = 9 },
    [661] = { encounterID = 661, encounterName = "Prince Malchezaar", instanceID = 532, alternativeTargets = {}, encounterIndex = 10 },
    [649] = { encounterID = 649, encounterName = "High King Maulgar", instanceID = 565, alternativeTargets = {}, encounterIndex = 1 },
    [650] = { encounterID = 650, encounterName = "Gruul the Dragonkiller", instanceID = 565, alternativeTargets = {}, encounterIndex = 2 },
    [651] = { encounterID = 651, encounterName = "Magtheridon", instanceID = 544, alternativeTargets = {}, encounterIndex = 1 },
    [624] = { encounterID = 624, encounterName = "The Lurker Below", instanceID = 548, alternativeTargets = {}, encounterIndex = 1 },
    [623] = { encounterID = 623, encounterName = "Hydross the Unstable", instanceID = 548, alternativeTargets = {}, encounterIndex = 2 },
    [625] = { encounterID = 625, encounterName = "Leotheras the Blind", instanceID = 548, alternativeTargets = {}, encounterIndex = 3 },
    [626] = { encounterID = 626, encounterName = "Fathom-Lord Karathress", instanceID = 548, alternativeTargets = {}, encounterIndex = 4 },
    [627] = { encounterID = 627, encounterName = "Morogrim Tidewalker", instanceID = 548, alternativeTargets = {}, encounterIndex = 5 },
    [628] = { encounterID = 628, encounterName = "Lady Vashj", instanceID = 548, alternativeTargets = {}, encounterIndex = 6 },
    [732] = { encounterID = 732, encounterName = "High Astromancer Solarian", instanceID = 550, alternativeTargets = {}, encounterIndex = 3 },
    [730] = { encounterID = 730, encounterName = "A'lar", instanceID = 550, alternativeTargets = {}, encounterIndex = 1 },
    [731] = { encounterID = 731, encounterName = "Void Reaver", instanceID = 550, alternativeTargets = {}, encounterIndex = 2 },
    [733] = { encounterID = 733, encounterName = "Kael'thas Sunstrider", instanceID = 550, alternativeTargets = {}, encounterIndex = 4 },
    [618] = { encounterID = 618, encounterName = "Rage Winterchill", instanceID = 534, alternativeTargets = {}, encounterIndex = 1 },
    [619] = { encounterID = 619, encounterName = "Anetheron", instanceID = 534, alternativeTargets = {}, encounterIndex = 2 },
    [620] = { encounterID = 620, encounterName = "Kaz'rogal", instanceID = 534, alternativeTargets = {}, encounterIndex = 3 },
    [621] = { encounterID = 621, encounterName = "Azgalor", instanceID = 534, alternativeTargets = {}, encounterIndex = 4 },
    [622] = { encounterID = 622, encounterName = "Archimonde", instanceID = 534, alternativeTargets = {}, encounterIndex = 5 },
    [601] = { encounterID = 601, encounterName = "High Warlord Naj'entus", instanceID = 564, alternativeTargets = {}, encounterIndex = 1 },
    [602] = { encounterID = 602, encounterName = "Supremus", instanceID = 564, alternativeTargets = {}, encounterIndex = 2 },
    [603] = { encounterID = 603, encounterName = "Shade of Akama", instanceID = 564, alternativeTargets = {}, encounterIndex = 3 },
    [604] = { encounterID = 604, encounterName = "Teron Gorefiend", instanceID = 564, alternativeTargets = {}, encounterIndex = 4 },
    [605] = { encounterID = 605, encounterName = "Reliquary of Souls", instanceID = 564, alternativeTargets = {}, encounterIndex = 5 },
    [606] = { encounterID = 606, encounterName = "Gurtogg Bloodboil", instanceID = 564, alternativeTargets = {}, encounterIndex = 6 },
    [607] = { encounterID = 607, encounterName = "Mother Shahraz", instanceID = 564, alternativeTargets = {}, encounterIndex = 7 },
    [608] = { encounterID = 608, encounterName = "The Illidari Council", instanceID = 564, alternativeTargets = { "Lady Malande", "Gathios the Shatterer", "Veras Darkshadow", "High Nethermancer Zerevor" }, encounterIndex = 8 },
    [609] = { encounterID = 609, encounterName = "Illidan Stormrage", instanceID = 564, alternativeTargets = {}, encounterIndex = 9 },
    [1189] = { encounterID = 1189, encounterName = "Akil'zon", instanceID = 568, alternativeTargets = {}, encounterIndex = 1 },
    [1190] = { encounterID = 1190, encounterName = "Nalorakk", instanceID = 568, alternativeTargets = {}, encounterIndex = 2 },
    [1191] = { encounterID = 1191, encounterName = "Jan'alai", instanceID = 568, alternativeTargets = {}, encounterIndex = 3 },
    [1192] = { encounterID = 1192, encounterName = "Halazzi", instanceID = 568, alternativeTargets = {}, encounterIndex = 4 },
    [1193] = { encounterID = 1193, encounterName = "Hex Lord Malacrass", instanceID = 568, alternativeTargets = {}, encounterIndex = 5 },
    [1194] = { encounterID = 1194, encounterName = "Zul'jin", instanceID = 568, alternativeTargets = {}, encounterIndex = 6 },
    [724] = { encounterID = 724, encounterName = "Kalecgos", instanceID = 580, alternativeTargets = {}, encounterIndex = 1 },
    [725] = { encounterID = 725, encounterName = "Brutallus", instanceID = 580, alternativeTargets = {}, encounterIndex = 2 },
    [726] = { encounterID = 726, encounterName = "Felmyst", instanceID = 580, alternativeTargets = {}, encounterIndex = 3 },
    [727] = { encounterID = 727, encounterName = "Eredar Twins", instanceID = 580, alternativeTargets = { "Lady Sacrolash", "Grand Warlock Alythess" }, encounterIndex = 4 },
    [728] = { encounterID = 728, encounterName = "M'uru", instanceID = 580, alternativeTargets = {}, encounterIndex = 5 },
    [729] = { encounterID = 729, encounterName = "Kil'jaeden", instanceID = 580, alternativeTargets = { "Hand of the Deceiver" }, encounterIndex = 6 },
}