InstancesDb = {
    [603] = { instanceID = 603, instanceName = "Ulduar", savedInstanceName = "Ulduar", instanceIndex = 1 },
    [533] = { instanceID = 533, instanceName = "Naxxramas", savedInstanceName = "Naxxramas", instanceIndex = 2 },
    [615] = { instanceID = 615, instanceName = "The Obsidian Sanctum", savedInstanceName = "The Obsidian Sanctum", instanceIndex = 3 },
    [616] = { instanceID = 616, instanceName = "The Eye of Eternity", savedInstanceName = "The Eye of Eternity", instanceIndex = 4 },
    [649] = { instanceID = 649, instanceName = "Trial of the Crusader", savedInstanceName = "Trial of the Crusader", instanceIndex = 5 },
}

EncountersDb = {
    [1107] = { encounterID = 1107, encounterName = "Anub'Rekhan", instanceID = 533, alternativeTargets = {}, encounterIndex = 1 },
    [1110] = { encounterID = 1110, encounterName = "Grand Widow Faerlina", instanceID = 533, alternativeTargets = {}, encounterIndex = 2 },
    [1116] = { encounterID = 1116, encounterName = "Maexxna", instanceID = 533, alternativeTargets = {}, encounterIndex = 3 },
    [1118] = { encounterID = 1118, encounterName = "Patchwerk", instanceID = 533, alternativeTargets = {}, encounterIndex = 4 },
    [1111] = { encounterID = 1111, encounterName = "Grobbulus", instanceID = 533, alternativeTargets = {}, encounterIndex = 5 },
    [1108] = { encounterID = 1108, encounterName = "Gluth", instanceID = 533, alternativeTargets = {}, encounterIndex = 6 },
    [1120] = { encounterID = 1120, encounterName = "Thaddius", instanceID = 533, alternativeTargets = { "Feugen", "Stalagg" }, encounterIndex = 7 },
    [1117] = { encounterID = 1117, encounterName = "Noth the Plaguebringer", instanceID = 533, alternativeTargets = {}, encounterIndex = 8 },
    [1112] = { encounterID = 1112, encounterName = "Heigan the Unclean", instanceID = 533, alternativeTargets = {}, encounterIndex = 9 },
    [1115] = { encounterID = 1115, encounterName = "Loatheb", instanceID = 533, alternativeTargets = {}, encounterIndex = 10 },
    [1113] = { encounterID = 1113, encounterName = "Instructor Razuvious", instanceID = 533, alternativeTargets = {}, encounterIndex = 11 },
    [1109] = { encounterID = 1109, encounterName = "Gothik the Harvester", instanceID = 533, alternativeTargets = {}, encounterIndex = 12 },
    [1121] = { encounterID = 1121, encounterName = "The Four Horsemen", instanceID = 533, alternativeTargets = { "Thane Korth'azz", "Lady Blaumeux", "Sir Zeliek", "Baron Rivendare"}, encounterIndex = 13 },
    [1119] = { encounterID = 1119, encounterName = "Sapphiron", instanceID = 533, alternativeTargets = {}, encounterIndex = 14 },
    [1114] = { encounterID = 1114, encounterName = "Kel'Thuzad", instanceID = 533, alternativeTargets = {}, encounterIndex = 15 },
    [1090] = { encounterID = 1090, encounterName = "Sartharion", instanceID = 615, alternativeTargets = {}, encounterIndex = 1 },
    [1094] = { encounterID = 1094, encounterName = "Malygos", instanceID = 616, alternativeTargets = {}, encounterIndex = 1 },
    [744] = { encounterID = 744, encounterName = "Flame Leviathan", instanceID = 603, alternativeTargets = {}, encounterIndex = 1 },
    [746] = { encounterID = 746, encounterName = "Razorscale", instanceID = 603, alternativeTargets = {}, encounterIndex = 2 },
    [745] = { encounterID = 745, encounterName = "Ignis the Furnace Master", instanceID = 603, alternativeTargets = {}, encounterIndex = 3 },
    [747] = { encounterID = 747, encounterName = "XT-002 Deconstructor", instanceID = 603, alternativeTargets = {}, encounterIndex = 4 },
    [748] = { encounterID = 748, encounterName = "Assembly of Iron", instanceID = 603, alternativeTargets = {}, encounterIndex = 5 },
    [757] = { encounterID = 757, encounterName = "Algalon the Observer", instanceID = 603, alternativeTargets = {}, encounterIndex = 6 },
    [749] = { encounterID = 749, encounterName = "Kologarn", instanceID = 603, alternativeTargets = {}, encounterIndex = 7 },
    [750] = { encounterID = 750, encounterName = "Auriaya", instanceID = 603, alternativeTargets = {}, encounterIndex = 8 },
    [751] = { encounterID = 751, encounterName = "Hodir", instanceID = 603, alternativeTargets = {}, encounterIndex = 9 },
    [752] = { encounterID = 752, encounterName = "Thorim", instanceID = 603, alternativeTargets = {}, encounterIndex = 10 },
    [753] = { encounterID = 753, encounterName = "Freya", instanceID = 603, alternativeTargets = {}, encounterIndex = 11 },
    [754] = { encounterID = 754, encounterName = "Mimiron", instanceID = 603, alternativeTargets = {}, encounterIndex = 12 },
    [755] = { encounterID = 755, encounterName = "General Vezax", instanceID = 603, alternativeTargets = {}, encounterIndex = 13 },
    [756] = { encounterID = 756, encounterName = "Yogg-Saron", instanceID = 603, alternativeTargets = {}, encounterIndex = 14 },
    [629] = { encounterID = 629, encounterName = "Northrend Beasts", instanceID = 649, alternativeTargets = {}, encounterIndex = 1 },
    [633] = { encounterID = 633, encounterName = "Lord Jaraxxus", instanceID = 649, alternativeTargets = {}, encounterIndex = 2 },
    [637] = { encounterID = 637, encounterName = "Faction Champions", instanceID = 649, alternativeTargets = {}, encounterIndex = 3 },
    [641] = { encounterID = 641, encounterName = "Val'kyr Twins", instanceID = 649, alternativeTargets = {}, encounterIndex = 4 },
    [645] = { encounterID = 645, encounterName = "Anub'arak", instanceID = 649, alternativeTargets = {}, encounterIndex = 5 },
}