name: Sample Build
on: [push]
jobs:
  run_build:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run build
        run: ./build.cmd build
      - name: List build files
        run: ls ./build